# app/services/sanction_pdf.py
from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path
import json
from typing import Dict, Any, Tuple

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.pdfgen.canvas import Canvas
from reportlab.graphics.barcode import qr

DATA_DIR = Path("/app/data")  # mounted in docker-compose
DATA_DIR.mkdir(parents=True, exist_ok=True)

def inr(n: float | int) -> str:
    # lightweight Indian formatting for demo
    s = f"{int(round(n)):,}"
    # convert 12,34,56,789 style (optional). Keep simple for now.
    return f"₹{s.replace(',', ',')}"

def compute_emi(p: float, apr: float, months: int) -> Tuple[int, int]:
    # apr is annual, e.g. 0.18 for 18%
    r = apr / 12.0
    if p <= 0 or months <= 0:
        return 0, 0
    f = (1 + r) ** months
    emi = int(round((p * r * f) / (f - 1)))
    total = emi * months
    return emi, total

def _header_footer(canvas: Canvas, doc):
    # Header ribbon
    canvas.saveState()
    w, h = A4
    canvas.setFillColorRGB(0.07, 0.14, 0.22)  # slate-900-ish
    canvas.rect(0, h - 26, w, 26, fill=True, stroke=False)

    canvas.setFillColorRGB(0.25, 0.93, 0.62)  # emerald accent
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(18, h - 18, "GreenLight Credit")
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(w - 18, h - 18, datetime.now().strftime("%d %b %Y %H:%M"))

    # Footer
    canvas.setStrokeColor(colors.lightgrey)
    canvas.setLineWidth(0.3)
    canvas.line(18, 24, w - 18, 24)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(18, 12, "Generated by GreenLight Orchestrator - Confidential")
    canvas.drawRightString(w - 18, 12, f"Page {doc.page}")

    canvas.restoreState()

def _chip(text: str) -> Table:
    t = Table([[text]], colWidths="*")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.Color(0.09, 0.36, 0.25, alpha=0.15)),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.Color(0.25, 0.93, 0.62, alpha=0.6)),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.Color(0.75, 1, 0.9)),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t

def build_sanction_pdf(
    session_id: str,
    payload: Dict[str, Any],
    out_dir: Path = DATA_DIR,
    apr: float = 0.18,
) -> Tuple[str, Dict[str, Any]]:
    """
    Builds a polished sanction letter and writes a KFS JSON alongside.

    Returns:
        (served_pdf_path, kfs_dict)
        served_pdf_path looks like "/files/sanction_<session>.pdf"
    """
    name = payload.get("name") or "Applicant"
    amount = int(payload.get("desired_amount") or 0)
    months = int(payload.get("tenure") or 0)
    salary = int(payload.get("salary") or 0)
    app_id = payload.get("application_id") or f"APP-{session_id[:6].upper()}"
    mandate_id = payload.get("mandate_id") or f"MDT-{session_id[:6]}"

    emi, total = compute_emi(amount, apr, months)
    proc_fee_rate = 0.015  # demo numbers
    gst_rate = 0.18
    processing_fee = int(round(amount * proc_fee_rate))
    gst = int(round(processing_fee * gst_rate))
    disbursal = amount - processing_fee - gst

    valid_until = (datetime.utcnow() + timedelta(days=7)).strftime("%d %b %Y")

    # KFS dict (what your UI shows and what we persist)
    kfs = {
        "Application ID": app_id,
        "Customer name": name,
        "Sanction amount": inr(amount),
        "Tenure (months)": months,
        "APR (p.a.)": f"{round(apr*100, 2)}%",
        "EMI": inr(emi),
        "Total payable": inr(total),
        "Processing fee": inr(processing_fee),
        "GST on PF": inr(gst),
        "Net disbursal": inr(disbursal),
        "Mandate ID": mandate_id,
        "Offer valid until": valid_until,
    }

    # File paths
    pdf_path = out_dir / f"sanction_{session_id}.pdf"
    kfs_path = out_dir / f"kfs_{session_id}.json"

    with open(kfs_path, "w", encoding="utf-8") as f:
        json.dump(kfs, f, ensure_ascii=False, indent=2)

    # Build PDF
    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm, topMargin=32*mm, bottomMargin=18*mm,
        title=f"Sanction Letter - {app_id}",
        author="GreenLight Credit",
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="H1",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.black,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="Sub",
        parent=styles["Normal"],
        fontSize=9.5,
        textColor=colors.grey,
    ))
    styles.add(ParagraphStyle(
        name="Kpi",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.Color(0.25, 0.93, 0.62),
    ))
    styles.add(ParagraphStyle(
        name="SecHead",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=colors.black,
        spaceBefore=10, spaceAfter=6,
    ))
    story = []

    story.append(_chip("Provisional Sanction"))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Sanction Letter", styles["H1"]))
    story.append(Paragraph(
        "This letter confirms the provisional sanction of your personal loan subject to verification and final documentation.",
        styles["Sub"],
    ))
    story.append(Spacer(1, 8))

    # KPI row
    kpi = Table([
        ["Sanction amount", "Tenure", "EMI", "APR"],
        [inr(amount), f"{months} months", inr(emi), f"{round(apr*100, 2)}% p.a."],
    ], colWidths=[90*mm/2, 50*mm/2, 50*mm/2, 50*mm/2])
    kpi.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.96, 0.97, 0.99)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.Color(0.3, 0.35, 0.5)),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.Color(0.86, 0.9, 0.96)),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.Color(0.9, 0.92, 0.96)),
        ("FONTSIZE", (0, 1), (-1, 1), 12),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 1), (-1, 1), colors.black),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
    ]))
    story.append(kpi)

    story.append(Spacer(1, 10))
    story.append(Paragraph("Applicant & Case Details", styles["SecHead"]))
    details = [
        ["Applicant name", name],
        ["Application ID", app_id],
        ["Monthly net salary", inr(salary)],
        ["Mandate ID", mandate_id],
        ["Offer valid until", valid_until],
    ]
    t = Table(details, colWidths=[45*mm, 110*mm])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
            [colors.white, colors.Color(0.98, 0.985, 0.995)]),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.Color(0.9, 0.92, 0.96)),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.Color(0.9, 0.92, 0.96)),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)

    story.append(Spacer(1, 10))
    story.append(Paragraph("Key Fact Statement (KFS)", styles["SecHead"]))
    kfs_rows = [
        ["Sanction amount", inr(amount)],
        ["Processing fee", inr(processing_fee)],
        ["GST on PF", inr(gst)],
        ["Net disbursal (to bank)", inr(disbursal)],
        ["Tenure", f"{months} months"],
        ["APR", f"{round(apr*100, 2)}% p.a."],
        ["EMI (indicative)", inr(emi)],
        ["Total payable (indicative)", inr(total)],
    ]
    k = Table(kfs_rows, colWidths=[60*mm, 95*mm])
    k.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ("BOX", (0, 0), (-1, -1), 0.6, colors.Color(0.9, 0.92, 0.96)),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.Color(0.9, 0.92, 0.96)),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
            [colors.white, colors.Color(0.98, 0.985, 0.995)]),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(k)

    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", color=colors.Color(0.9, 0.92, 0.96), thickness=0.6))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Important terms (summary)", styles["SecHead"]))
    terms = [
        "Offer is subject to successful KYC, bureau, income and bank-statement verification.",
        "Fees and APR are indicative for this letter. Final agreement supersedes these numbers.",
        "Repayment through NACH/mandate. Pre-closure/part-payment as per policy.",
        "This letter is system-generated and does not require a physical signature."
    ]
    for tline in terms:
        story.append(Paragraph(f"• {tline}", styles["Normal"]))
    story.append(Spacer(1, 10))

    # Signature and QR row
    sig = Table([
        ["Authorized Signatory", ""],
        ["GreenLight Credit", ""],
    ], colWidths=[70*mm, 85*mm])
    sig.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("LINEABOVE", (0, 0), (0, 0), 0.6, colors.grey),
        ("LINEABOVE", (0, 1), (0, 1), 0.6, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
    ]))

    # QR that points to a hypothetical verification URL
    verify_url = f"https://example.com/verify/{app_id}"
    code = qr.QrCodeWidget(verify_url)
    bounds = code.getBounds()
    size = 26*mm
    w = bounds[2] - bounds[0]
    h = bounds[3] - bounds[1]
    # embed QR as small table cell using a drawing on the canvas after build
    qr_tbl = Table([[code]], colWidths=[size], rowHeights=[size])
    qr_tbl.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))

    bottom = Table([[sig, qr_tbl]], colWidths=[125*mm, 30*mm])
    bottom.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(bottom)

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)

    served = f"/files/{pdf_path.name}"
    return served, kfs
